## Deliverable 2. Create a Customer Travel Destinations Map.

In [68]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [69]:
# 1. Import the WeatherPy_database.csv file. 
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

#     **** THIS NEEDS TO BE LINKED TO CSV FROM WEATHERPY*******

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Itapicuru,-11.3167,-38.2333,75.04,86,12,8.66
1,1,Kruisfontein,-34.0033,24.7314,64.89,96,100,3.13
2,2,East London,-33.0153,27.9116,73.31,85,100,12.33
3,3,Atuona,-9.8000,-139.0333,78.06,78,29,16.60
4,4,Victoria,22.2855,114.1577,59.32,78,100,3.00

In [70]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

In [71]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Itapicuru,-11.3167,-38.2333,75.04,86,12,8.66
2,2,East London,-33.0153,27.9116,73.31,85,100,12.33
3,3,Atuona,-9.8000,-139.0333,78.06,78,29,16.60
5,5,Nauta,-4.5061,-73.5757,75.60,75,100,0.34
9,9,Harper,4.3750,-7.7169,78.84,85,76,5.03
10,10,Santo Amaro Da Imperatriz,-27.6881,-48.7786,73.22,91,88,1.83
11,11,Saint-Philippe,-21.3585,55.7679,74.79,86,52,10.54
12,12,Padang,-0.9492,100.3543,75.25,83,100,3.24
13,13,Samana,19.2056,-69.3369,73.26,85,13,3.91
14,14,Busselton,-33.6500,115.3333,70.05,51,100,18.61

In [72]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID       253
City          253
Lat           253
Lng           253
Max Temp      253
Humidity      253
Cloudiness    253
Wind Speed    253
dtype: int64

In [73]:
preferred_cities_df.values

array([[0, 'Itapicuru', -11.3167, ..., 86, 12, 8.66],
       [2, 'East London', -33.0153, ..., 85, 100, 12.33],
       [3, 'Atuona', -9.8, ..., 78, 29, 16.6],
       ...,
       [846, 'Yangambi', 0.8102, ..., 39, 100, 2.48],
       [847, 'Mainit', 9.535, ..., 76, 100, 3.27],
       [850, 'Boende', -0.2167, ..., 35, 100, 2.15]], dtype=object)

In [75]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

KeyError: "['Country'] not in index"

In [61]:
# 6a. Set parameters to search for hotels with 5000 meters.
gmaps.configure(api_key=g_key)
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [62]:
# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        print(hotel_df.loc[index, "Hotel Name"])
    except (IndexError):
        print("Hotel not found... skipping.")

Diego De Almagro Coyhaique
Ellie's Villa
Misty Waves Boutique Hotel
39 On Nile Guest House
Hotel Hain
Hotel Chik Chik Namibe
Finch Bay Galapagos Hotel
Hotel Villa Kitzia Huacho
Hilo Hawaiian Hotel
Lovers Point Inn
Hotel Castelo
The Halyards Hotel
Shyam Dhar Yadav Shiv dhar Yadav
CHACARA BAILLY
Hotel Irpinia
Posada Villaven C.A.
Baymont by Wyndham Lazaro Cardenas
Bluff Homestead - Guesthouse & Campervan Park
Hotel Xaguate
Tu Casa
Hostal Las Lilas
Hotel De Paris
Gran Hotel Mar del Plata
Mantra on Collins Hobart
departamento comodo
Oyster Bay House Rental
Blendana Hotel Assosa
Scenic Hotel Southern Cross
Vila Nova Hotel
Hotel not found... skipping.
Bredasdorp Country Manor
Siang Guest House
Kaitangata Motor Camp
Hotel do Campo
Ron and Tony's Bed & Breakfast
The Esplanade Resort & Spa
Hotel Premier
Euskadi Hotel
H10 Taburiente Playa
Nuevo Hotel Plaza
Southern Sun Waterfront Cape Town
La Quinta Inn & Suites by Wyndham Buena Park
Bom Será - Marcinho e Fernanda
OCHA Office
Mini Hotel Central
Playa Linda Hotel
Pousada Buterfly
El Medina
Hotel San Isidro Oficial
Sur Plaza Hotel
Quinta da Meia Eira
Hotel Patagonia
Casa do Kiwliks
Hotel Pousada Tropical
Pestana Bahia Praia
Valle Aridane
Hotel Atoll Emerald Miyakojima
Blue Bay Lodge
Rim touristique hôtel
Hotel not found... skipping.
Hotel Narayan Avezika Comfort
Hotel Tesoro Los Cabos
Gold Star International Hotel
Paradise Hotel
Otway Gate Motel
Residência Ulisses Dos Santos
Hotel not found... skipping.
Whispering Bamboo Cove Resort
Hotel not found... skipping.
The Shingles Riverside Cottages
BON Hotel Waterfront Richards Bay
Hotel Pigalle
Holiday Inn Express Lompoc, an IHG Hotel
Hotel Colonial
Hotel not found... skipping.
Hotel not found... skipping.
The Ritz-Carlton, Half Moon Bay
Zango lodge
Tora Coastal Walk
RISO HOTEL
JABIR HOTEL
Miraval Arizona Resort & Spa
Dorendro Yengkhom's Shanghai
Casa Das Faias
Palace hotel
La pousada
Miarina
Treebo Trend Sky Dale Inn & Suites Ooty Lake
Hotel not found... skipping.
Hotel not found... skipping.
Hotel Festival Plaza Rosarito
Sharif Plaza Hotel
Hotel Alejandro I
Melrose
Hotel Santa Cruz
Hotel Mout View
Apartamentos Rincon La Roca
Hotel Boutique Las Azucenas
Mwitongo Lodge
Hotel e Restaurante Aҫai
Pousada Vale do magu
INN NEW HORIZON
GKT Hotel
Casa Laguna, Bed & Breakfast
Hotel not found... skipping.
Shishime Hotel
Hotel not found... skipping.
Residence Inn by Marriott Cape Canaveral Cocoa Beach
Hotel not found... skipping.
Amiin Hotel
Hotel Montesclaros
Paihuen
Port Lincoln Hotel
El rranchito michuacan de ocampos
Hôtel Le Dronmi
Hostal Morales
Hotel Pekassa De Karche
Codrington Gardens Bed And Breakfast
Hotel Albergue de Olinda
Hotel not found... skipping.
Ditlhapi Guest House
Residencial Karime
Urafiki House
POUSADA TRAVÉS'CIA
Radisson Grenada Beach Resort
Hostel Del Puerto
Las Cabinas Del Sueño
Kirari Guest House
Hotel not found... skipping.
Phama Lodge
Hotel Vision
Pousada Da Praia
Die Lemoenhuis
AYAR PORTENTOS DE MONTAÑA
Casa da Oscarina
Hotel not found... skipping.
janelas do mar
Crystal Beach and Camping Resort Ormara
Casa- Bernardo Cândido
Gran Hotel Bolivar Lima
Hôtel Trois Étoiles de Biltine
Southern Beach Hotel & Resort Okinawa
Casa de Campo Resort and Villas
The Trident Hotel
مزرعة راحة النفوس المنزفة
Résidence Okanda
HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel
Kingsgate Hotel Te Anau
Hotel "La Casa Embrujada"
Eastwood Guesthouse
Oumou Elghoura
Hotel Galvarino
Playa Punta Yaya - Las Salinas
Don Eddie's Landing
Sheraton Gambia Hotel Resort & Spa
Rancho Crepusculo
Wasai Hotel
Hotel not found... skipping.
Bus group international
Hotel Branco I
Hotel hewa bora
Hotel Suiza
Hotel Emirates
Aviador Hotel Boutique
Hotel Atlântico Rio Grande
Banjanay Hotel
Tolaga Bay Motel
Melrose Place Guestrooms
हंसराज ट्रैक्टर
Xiamen Dongchen Hotel
Hôtel Tshia-Muntu de Tshikapa
Case de Passage De la Prefecture
Pousada Maria Bonita
Hotel not found... skipping.
Hotel Missões
Praia Hotel Imbituba
Hospedaje Costa Bella

7. Drop the rows where there is no Hotel Name.
DROPNA

In [67]:
hotels_df

NameError: name 'hotels_df' is not defined

In [54]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [55]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Temperature</dt><dd> {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [63]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

SAVE FIGURE